- hosts: packstack
  become: true
  tasks:
    - name: Disabling services
      systemd:
        enabled: no
        state: stopped
        name: "{{ item }}"
      with_items:
        - firewalld
        - NetworkManager
    - name: Enable network
      systemd:
        enabled: yes
        state: started
        name: network
    - name: Install RDO Repo
      yum:
        name: https://rdoproject.org/repos/rdo-release.rpm
        state: present
    - name: Install Extras
      yum:
        name: centos-release-openstack-pike
        state: present
    - name: Update system
      yum:
        name: '*'
        state: latest
    - name: Install Packstack Installer
      yum:
        name: openstack-packstack
        state: present
    - name: Create user stack
      user:
        name: stack
        groups: wheel
        password: CODEDSTRINGHERE
